# Generated by Django 2.2.5 on 2020-04-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_nam', models.CharField(max_length=10)),
                ('last_nam', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_nam', models.CharField(max_length=5)),
                ('last_nam', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('specialization', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
            ],
        ),
        migrations.CreateModel(
            name='weeklypresentation',
            fields=[
                ('weeklypresentationid', models.AutoField(primary_key=True, serialize=False)),
                ('weektopic', models.CharField(max_length=100)),
                ('weekduration', models.PositiveIntegerField(blank=True, null=True)),
                ('weekdate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('visitorsid', models.AutoField(primary_key=True, serialize=False)),
                ('visitorscount', models.PositiveIntegerField(blank=True, null=True)),
                ('visitorstopic', models.CharField(max_length=100)),
                ('visitorsduration', models.PositiveIntegerField(blank=True, null=True)),
                ('visitorsdate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='socials',
            fields=[
                ('socialsid', models.AutoField(primary_key=True, serialize=False)),
                ('socialsplace', models.CharField(max_length=100)),
                ('socialstopic', models.CharField(max_length=100)),
                ('socialsduration', models.PositiveIntegerField(blank=True, null=True)),
                ('socialsdate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='referralstaken',
            fields=[
                ('referralstakenid', models.AutoField(primary_key=True, serialize=False)),
                ('takencount', models.PositiveIntegerField(blank=True, null=True)),
                ('takentopic', models.CharField(max_length=100)),
                ('takenduration', models.PositiveIntegerField(blank=True, null=True)),
                ('takendate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='referralsgiven',
            fields=[
                ('referralsgivenid', models.AutoField(primary_key=True, serialize=False)),
                ('givencount', models.PositiveIntegerField(blank=True, null=True)),
                ('giventopic', models.CharField(max_length=100)),
                ('givenduration', models.PositiveIntegerField(blank=True, null=True)),
                ('givendate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='onetoone',
            fields=[
                ('onetooneid', models.AutoField(primary_key=True, serialize=False)),
                ('partner', models.CharField(max_length=20)),
                ('onetopic', models.CharField(max_length=100)),
                ('oneduration', models.PositiveIntegerField(blank=True, null=True)),
                ('onedate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='dailypresentation',
            fields=[
                ('dailypresentationid', models.AutoField(primary_key=True, serialize=False)),
                ('dailytopic', models.CharField(max_length=100)),
                ('dailyduration', models.PositiveIntegerField(blank=True, null=True)),
                ('dailydate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
    ]
