# Generated by Django 2.2.5 on 2020-07-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='weeklypresentation',
            fields=[
                ('weeklypresentationid', models.AutoField(primary_key=True, serialize=False)),
                ('weektopic', models.CharField(max_length=100)),
                ('weekduration', models.PositiveIntegerField(blank=True, null=True)),
                ('weekdate', models.DateField(null=True)),
                ('weekbestby', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('visitorsid', models.AutoField(primary_key=True, serialize=False)),
                ('visitorstopic', models.CharField(max_length=100)),
                ('visitorsnumbers', models.PositiveIntegerField(blank=True, null=True)),
                ('visitorsdate', models.DateField(null=True)),
                ('visitorspic', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='trainings',
            fields=[
                ('trainingid', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('subject', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='sphere',
            fields=[
                ('sphereid', models.AutoField(primary_key=True, serialize=False)),
                ('spherename', models.CharField(max_length=100)),
                ('spherenumber', models.CharField(max_length=100)),
                ('spheremail', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='socials',
            fields=[
                ('socialsid', models.AutoField(primary_key=True, serialize=False)),
                ('socialsplace', models.CharField(max_length=100, null=True)),
                ('socialstopic', models.CharField(max_length=100)),
                ('socialsdate', models.DateField(null=True)),
                ('socialspic', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='referralstaken',
            fields=[
                ('referralstakenid', models.AutoField(primary_key=True, serialize=False)),
                ('takentopic', models.CharField(max_length=100)),
                ('takenduration', models.PositiveIntegerField(blank=True, null=True)),
                ('takendate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='referralsgiven',
            fields=[
                ('referralsgivenid', models.AutoField(primary_key=True, serialize=False)),
                ('givenby', models.CharField(max_length=100)),
                ('giventype', models.CharField(max_length=100)),
                ('givenaddress', models.CharField(max_length=100)),
                ('givenphonenumber', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='onetoone',
            fields=[
                ('onetooneid', models.AutoField(primary_key=True, serialize=False)),
                ('onemet', models.CharField(max_length=20, null=True)),
                ('oneinvited', models.CharField(max_length=20, null=True)),
                ('oneratings', models.CharField(max_length=20, null=True)),
                ('onetopic', models.CharField(max_length=100)),
                ('onedate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='need',
            fields=[
                ('trainingid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='jvtthankyou',
            fields=[
                ('jvtthankyouid', models.AutoField(primary_key=True, serialize=False)),
                ('youto', models.CharField(max_length=100)),
                ('youamount', models.CharField(max_length=100)),
                ('youbtype', models.CharField(max_length=100)),
                ('yourtype', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('recname', models.CharField(max_length=100)),
                ('recexp', models.CharField(max_length=100)),
                ('recctc', models.CharField(max_length=100)),
                ('recdate', models.DateField(null=True)),
                ('reccomname', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='invited',
            fields=[
                ('invitedid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('vcompanyname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('companyname', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('interviewid', models.AutoField(primary_key=True, serialize=False)),
                ('metwith', models.CharField(max_length=100)),
                ('inviteby', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('topic', models.CharField(max_length=100)),
                ('Date', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='edittable',
            fields=[
                ('edittableid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('englishlevel', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Profession', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('joindate', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('projects', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('resume', models.FileField(upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_image')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='dailypresentation',
            fields=[
                ('dailypresentationid', models.AutoField(primary_key=True, serialize=False)),
                ('dailytopic', models.CharField(max_length=100)),
                ('dailyduration', models.CharField(max_length=100)),
                ('dailydate', models.DateField(null=True)),
                ('dailybestby', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
    ]
