# Generated by Django 2.2.5 on 2020-03-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_nam', models.CharField(max_length=10)),
                ('last_nam', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_nam', models.CharField(max_length=5)),
                ('last_nam', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('username', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('specialization', models.CharField(max_length=20)),
                ('image', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='weeklypresentation',
            fields=[
                ('weeklypresentationid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('weektopic', models.CharField(max_length=100)),
                ('weekduration', models.PositiveIntegerField(blank=True, null=True)),
                ('weekdate', models.DateField(null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='onetoone',
            fields=[
                ('onetooneid', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('partner', models.CharField(max_length=20)),
                ('onetopic', models.CharField(max_length=100)),
                ('oneduration', models.PositiveIntegerField(blank=True, null=True)),
                ('onedate', models.DateField(null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
    ]
