# Generated by Django 2.2.5 on 2020-04-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image'),
        ),
    ]
