# Generated by Django 2.2.5 on 2020-06-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypresentation',
            name='dailyduration',
            field=models.TimeField(),
        ),
    ]
