# Generated by Django 2.2.5 on 2020-05-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetoone',
            name='onemet',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
