# Generated by Django 2.2.5 on 2020-03-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0002_auto_20200323_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onetoone',
            old_name='userid',
            new_name='user',
        ),
    ]
