# Generated by Django 2.2.5 on 2020-06-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0002_auto_20200612_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypresentation',
            name='dailydate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
