# Generated by Django 2.2.5 on 2020-05-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0002_onetoone_onemet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetoone',
            name='oneduration',
        ),
        migrations.AddField(
            model_name='onetoone',
            name='onelocation',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
