# Generated by Django 2.2.5 on 2020-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0003_auto_20200617_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailypresentation',
            name='dailydate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dailypresentation',
            name='dailyduration',
            field=models.CharField(max_length=100),
        ),
    ]
