# Generated by Django 2.2.5 on 2020-03-30 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0004_auto_20200329_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('visitorsid', models.AutoField(primary_key=True, serialize=False)),
                ('visitorscount', models.PositiveIntegerField(blank=True, null=True)),
                ('visitorstopic', models.CharField(max_length=100)),
                ('visitorsduration', models.PositiveIntegerField(blank=True, null=True)),
                ('visitorsdate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='socials',
            fields=[
                ('socialsid', models.AutoField(primary_key=True, serialize=False)),
                ('socialsplace', models.CharField(max_length=100)),
                ('socialstopic', models.CharField(max_length=100)),
                ('socialsduration', models.PositiveIntegerField(blank=True, null=True)),
                ('socialsdate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='referralstaken',
            fields=[
                ('referralstakenid', models.AutoField(primary_key=True, serialize=False)),
                ('takencount', models.PositiveIntegerField(blank=True, null=True)),
                ('takentopic', models.CharField(max_length=100)),
                ('takenduration', models.PositiveIntegerField(blank=True, null=True)),
                ('takendate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='referralsgiven',
            fields=[
                ('referralsgivenid', models.AutoField(primary_key=True, serialize=False)),
                ('givencount', models.PositiveIntegerField(blank=True, null=True)),
                ('giventopic', models.CharField(max_length=100)),
                ('givenduration', models.PositiveIntegerField(blank=True, null=True)),
                ('givendate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='dailypresentation',
            fields=[
                ('dailypresentationid', models.AutoField(primary_key=True, serialize=False)),
                ('dailytopic', models.CharField(max_length=100)),
                ('dailyduration', models.PositiveIntegerField(blank=True, null=True)),
                ('dailydate', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
    ]
