# Generated by Django 2.2.5 on 2020-06-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0004_auto_20200617_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypresentation',
            name='weekbestby',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
