# Generated by Django 2.2.5 on 2020-06-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0005_weeklypresentation_weekbestby'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='socialspic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
