# Generated by Django 2.2.5 on 2020-06-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0006_socials_socialspic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socials',
            name='socialsduration',
        ),
        migrations.AddField(
            model_name='socials',
            name='socialsplace',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
