# Generated by Django 2.2.5 on 2020-06-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0007_auto_20200620_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='visitorsduration',
            new_name='visitorsnumbers',
        ),
        migrations.AddField(
            model_name='visitors',
            name='visitorspic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
