# Generated by Django 2.2.5 on 2020-06-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0008_auto_20200621_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralsgiven',
            old_name='giventopic',
            new_name='givenaddress',
        ),
        migrations.RemoveField(
            model_name='referralsgiven',
            name='givendate',
        ),
        migrations.RemoveField(
            model_name='referralsgiven',
            name='givenduration',
        ),
        migrations.AddField(
            model_name='referralsgiven',
            name='givenby',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralsgiven',
            name='givenphonenumber',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referralsgiven',
            name='giventype',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
