# Generated by Django 2.2.5 on 2020-06-23 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0009_auto_20200621_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='jvtthankyou',
            fields=[
                ('jvtthankyouid', models.AutoField(primary_key=True, serialize=False)),
                ('youto', models.CharField(max_length=100)),
                ('youamount', models.CharField(max_length=100)),
                ('youbtype', models.CharField(max_length=100)),
                ('yourtype', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
    ]
