# Generated by Django 2.2.5 on 2020-06-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0011_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='sphere',
            fields=[
                ('sphereid', models.AutoField(primary_key=True, serialize=False)),
                ('spherename', models.CharField(max_length=100)),
                ('spherenumber', models.CharField(max_length=100)),
                ('spheremail', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
    ]
