# Generated by Django 2.2.5 on 2020-06-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0012_sphere'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainings',
            fields=[
                ('trainingid', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('subject', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
    ]
