# Generated by Django 2.2.5 on 2020-06-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onemoreapp', '0013_trainings'),
    ]

    operations = [
        migrations.CreateModel(
            name='invited',
            fields=[
                ('invitedid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('vcompanyname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('companyname', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('interviewid', models.AutoField(primary_key=True, serialize=False)),
                ('metwith', models.CharField(max_length=100)),
                ('inviteby', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('topic', models.CharField(max_length=100)),
                ('Date', models.DateField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onemoreapp.users')),
            ],
        ),
    ]
